steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    secretEnv:
      - "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
      - "NEXT_PUBLIC_MAPS_BROWSER_KEY"
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_URI="us-central1-docker.pkg.dev/$PROJECT_ID/michi-backend/michi-backend:$COMMIT_SHA"
        docker build \
          --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY \
          --build-arg NEXT_PUBLIC_MAPS_BROWSER_KEY=$$NEXT_PUBLIC_MAPS_BROWSER_KEY \
          -t "$IMAGE_URI" \
          -f Dockerfile \
          .

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_URI="us-central1-docker.pkg.dev/$PROJECT_ID/michi-backend/michi-backend:$COMMIT_SHA"
        docker push "$IMAGE_URI"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_URI="us-central1-docker.pkg.dev/$PROJECT_ID/michi-backend/michi-backend:$COMMIT_SHA"
        gcloud run deploy michi-backend \
          --image "$IMAGE_URI" \
          --region "us-central1" \
          --platform "managed" \
          --quiet

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY/versions/latest"
      env: "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
    - versionName: "projects/$PROJECT_ID/secrets/NEXT_PUBLIC_MAPS_BROWSER_KEY/versions/latest"
      env: "NEXT_PUBLIC_MAPS_BROWSER_KEY"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/michi-backend/michi-backend:$COMMIT_SHA"
